### ISSUE TITLE
How can I remove an Egg?

### ISSUE THREAD

**Issue by tg247** [mikeflynn/egg.js#12]
Hi @mikeflynn,

I really like your plugin.

In my case, I would like to use this Egg only, if a jQuery Modal is opened. This already works fine.

``` javascript
$(document).on('opened', bullseye, function () {
  var eggBullseyeLeft = new Egg();
    eggBullseyeLeft
        .addCode("left", function(){switchBullTab("left")}, 'eggBullseyeLeft')
        .listen();
});
```

My problem is, that I don't want the Egg to be executed, when the modal is closed. I've tried to overwrite the var eggBullseyeLeft with an empty string or with an empty function like here:

``` javascript
$(document).on('closed', bullseye, function () {
  var eggBullseyeLeft = new Egg();
    eggBullseyeLeft
      .addCode("left", function(){}, 'eggBullseyeLeft')
      .listen();
});
```

But the original switchBullTab is still being triggered.
Can you please help me, how to remove the Egg?

Thank you very much for your effort.

Best regards,
Thomas

**Comment by mikeflynn** [comment]
You could dip in to the eggs array in the Egg object to remove a function but you'd have to loop through and look for the one you want to remove. 

In your specific case there are two things I would do: 
1. Pull the egg definition out of the functions you are tying to the modal actions.
2. Use a boolean flag that reflects the modal's state and trigger the different action accordingly.

For example...

``` javascript
var modalOpen = false;

var egg = new Egg();
egg.addCode("left", function() {
  if modalOpen === true {
    switchBullTab("left");
  }
}, 'eggBullseyeLeft').listen();

$(document).on('closed', bullseye, function () {
  modalOpen = false
});

$(document).on('opened', bullseye, function () {
  modalOpen = true;
});
```

...there may be a way, depending on the modal implementation, to query the modal element directly and see if it's visible rather than set the `modalOpen` flag, but this works.

**Comment by tg247** [comment]
Ok @mikeflynn, thanks for your suggestion.

"You could dip in to the eggs array in the Egg object to remove a function but you'd have to loop through and look for the one you want to remove."

How can I loop through the eggs? I have several Eggs, initialized after DOM-ready. When I want to list them

``` javascript
window.eggs
```

there are no eggs although the eggs are working.

Thank you very much for your effort.

**Comment by mikeflynn** [comment]
This depends on how you implemented the library. The eggs array is in the Egg object and if you are creating new Egg objects for each easter egg, then the eggs array will just have one egg each. However, if you are creating one Egg object and adding all of your eggs to that object, all of your eggs will be in the array.

Example:

``` javascript
// Create an egg object
var egg = new Egg();

// Add an easter egg
egg.addCode("left", function() {
  if modalOpen === true {
    switchBullTab("left");
  }
}, 'eggBullseyeLeft').listen();

// Add a second egg
egg.addCode("up,up,down,down,left,right,b,a", function() {
  alert("Boosh!");
}).listen();

// Loop through the eggs
for (var x in egg.eggs) {
  console.log(egg.eggs[x]);
}
```

**Comment by tg247** [comment]
perfect, you really helped me out! thank you very much :)
