### ISSUE TITLE
Could you help me add the version tag?

### ISSUE THREAD

**Issue by nolsherry** [mikeflynn/egg.js#13]
Hi @mikeflynn, I am the member of [cdnjs](https://github.com/cdnjs/cdnjs), and we wants to host  this repository. However, I found that that there is not any tag about this repository,
Could you help me add the version tag? Thanks! 
![image](https://cloud.githubusercontent.com/assets/8747900/21180949/65c8ba40-c236-11e6-9b39-2a199d34309c.png)

cdnjs/cdnjs#9363

**Comment by mikeflynn** [comment]
You just need a 1.0 version tag at the current master HEAD?

**Comment by nolsherry** [comment]
@mikeflynn Yes! Thank you very much.

**Comment by mikeflynn** [comment]
All set!

**Comment by maruilian11** [comment]
Hi @mikeflynn, could you please also keep adding git tags for this lib in the future, if you are going to release new version. Because our auto-update mechanism depend on the git tags. Thank you very much!

**Comment by mikeflynn** [comment]
Can do!
