### ISSUE TITLE
Doesn't recognize the § character

### ISSUE THREAD

**Issue by Olian04** [mikeflynn/egg.js#16]
This doesn't fire.
```javascript
new Egg("§", function() {
    console.log('Pressed §');
}).listen();
```

**Comment by mikeflynn** [comment]
Right. The reason for this is the following block:
```js

var isLetter = keyCode >= 65 && keyCode <= 90;
/*
  This prevents find as you type in Firefox.
  Only prevent default behavior for letters A-Z.
  I want keys like page up/down to still work.
*/
if ( e.type === "keydown" && !e.metaKey && !e.ctrlKey && !e.altKey && !e.shiftKey ) {
  var tag = e.target.tagName;

  if ( ( tag === "HTML" || tag === "BODY" ) && isLetter ) {
    e.preventDefault();
    return;
  }
}
```

We purposely avoided tracking keys that use modifiers or special keys to avoid stepping on system or other (I'll just say it: actually useful) keyboard shortcuts. There is an argument that's the current approach is too strong, but that's the reason keys like § (alt-6) are being ignored.
