### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by Arkni** [mikeflynn/egg.js#2]
Hi @mikeflynn 

In [bower.json](https://github.com/mikeflynn/egg.js/blob/master/bower.json#L15) say that it's MIT License, but [package.json](https://github.com/mikeflynn/egg.js/blob/master/package.json#L22) say it's ISC License.

Could you clarify which it is and, if possible, also add a LICENSE file ?

**Comment by mikeflynn** [comment]
Yes, great point. I can get a LICENSE in there today.

**Comment by rmcvey** [comment]
@Arkni @mikeflynn Sorry for the confusion, the license is MIT. I've updated the egg.js source to include the MIT license and updated the package.json with the MIT license.

**Comment by Arkni** [comment]
@rmcvey 
Thanks :)

**Comment by mikeflynn** [comment]
Explicit LICENSE.md file created as well.

**Comment by Arkni** [comment]
@mikeflynn 
Thanks :)
