### ISSUE TITLE
Why are the method names capitalized?

### ISSUE THREAD

**Issue by danieldiekmeier** [mikeflynn/egg.js#3]
I was just wondering why you decided to use `AddCode()` instead of `addCode()`.

**Comment by mikeflynn** [comment]
Ha, great question. I've been writing a lot of Go code lately and their standard seeped in to my Javascript that day. Not an exciting answer, but that's definitely what happened and @rmcvey asked me the same thing, we just haven't felt the urge to change them yet.

**Comment by danieldiekmeier** [comment]
Yes, it's not really important, of course. Just wondered. :D

**Comment by rmcvey** [comment]
@danieldiekmeier FWIW I added the lowercase method names to master (https://github.com/mikeflynn/egg.js/commit/dfb4183821600a619233a5607974ee2c8da9483a). We can't really remove the capitalized methods quite yet, but the documentation is now using the lowercase method names.

**Comment by danieldiekmeier** [comment]
Nice work, thank you!
